name: Celestecord Hourly Ping Collection

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  run_monitor_script:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v6

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: 🛠️ Install Dependencies
        run: pip install -r requirements.txt

      - name: 🚀 Run Collection Script
        env:
          PYTHONPATH: src
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          TARGET_WEBHOOK_URL: ${{ secrets.TARGET_WEBHOOK_URL }}
          STATE_SHEET_ID: ${{ secrets.STATE_SHEET_ID }}
          ACHIEVEMENTS_CHANNEL_IDS: ${{ secrets.ACHIEVEMENTS_CHANNEL_IDS }}
          TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
          HARD_CLEARS_ROLE_IDS: ${{ secrets.HARD_CLEARS_ROLE_IDS }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
        run: python -m collector
